In [98]:
from sklearn.cluster import KMeans
import pandas as pd
import hdbscan
import json
import numpy as np
from scipy.spatial import distance
from sklearn.manifold import TSNE

In [162]:
tsne_result=pd.read_csv('results_TSNE_2d.csv')
tsne_2d=tsne_result.drop(['Unnamed: 0'], axis=1)
tsne_train=pd.read_csv('tsne_train.csv')
plotly_text=tsne_result['img']

In [4]:
#hdbscan with no pre-specified no. of clusters
def hdbscan_cluster (dataframe):
    clusterer = hdbscan.HDBSCAN()
    clusterer.fit(dataframe)
    return clusterer.labels_

hdbscan_cluster(tsne_2d)

array([-1,  5,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  2,  5,  5, -1, -1, -1, -1,  2,  5,  5,  5, -1,
       -1,  5,  5, -1,  5,  5,  5, -1,  5,  5,  5,  5,  5,  5,  2,  0,  5,
        5, -1,  5,  5, -1, -1,  2, -1, -1,  5,  5,  5,  5,  5, -1,  5,  2,
        5, -1,  5,  2,  5,  2, -1, -1,  5,  5,  5,  2,  5, -1,  2,  5,  5,
        5, -1,  5,  1,  5,  2,  5, -1,  0,  0,  0,  5,  5,  5,  1, -1,  5,
        5,  2,  2,  2,  2,  0,  5,  5,  0,  5,  5,  2,  0,  5, -1,  5,  1,
       -1, -1, -1,  1, -1,  4,  1,  5,  5,  5, -1,  5, -1,  5, -1,  1, -1,
        2,  2,  1,  0,  2,  5, -1,  2,  5,  5, -1, -1,  2,  1, -1,  5, -1,
       -1,  2,  2,  5, -1, -1,  5, -1, -1,  2,  2,  5,  1,  1,  5, -1, -1,
        2, -1, -1, -1,  5, -1, -1,  5, -1,  5,  1, -1,  1, -1,  5,  5])

In [190]:
user_input_vector=[10. , 0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 1. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0.5, 0.5, 0. , 0. , 0.5,
        0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. ]
df_uservector=pd.DataFrame(user_input_vector)
df_uservector

        0
0    10.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.5
6     0.0
7     0.5
8     1.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.5
21    0.5
22    0.5
23    0.0
24    0.0
25    0.5
26    0.5
27    0.0
28    0.0
29    0.0
..    ...
115   0.0
116   0.0
117   0.0
118   0.0
119   0.0
120   0.0
121   0.0
122   0.0
123   0.0
124   0.0
125   0.0
126   0.0
127   0.0
128   0.0
129   0.0
130   0.0
131   0.0
132   0.0
133   0.0
134   0.0
135   0.0
136   0.0
137   0.0
138   0.0
139   0.0
140   0.0
141   0.0
142   0.0
143   0.0
144   0.0

[145 rows x 1 columns]

In [202]:


# def do_TSNE(data,df_uservector, output_dims, verbose=2, perplexity=30):
#     """
#     Reduce the dimensionaly from data.colmns into to output_dims
#     Returns a numpy array of (len(data), output_dims)    
#     """
#     with_user=data.append(df_uservector)
#     tsne = TSNE(n_components=output_dims, random_state=0, verbose=verbose, perplexity=perplexity)
#     data_2d = tsne.fit_transform(with_user)
    
#     return data_2d
    

# tsne_with_user = do_TSNE(final_df, 2,user_input_vector)

In [201]:
#Kmeans on TSNE RESULTS
# def k_means_process (df, n_cluster):
    
def kmeans_df_labels(df, n_cluster): #create a tsne result dataframe with Kmeans cluster label 
    
    km_df=df[["x","y"]].to_numpy()
    Kmeans_result=KMeans(n_clusters=n_cluster, random_state = 0).fit(km_df)
    labels= Kmeans_result.labels_
    df['labels']=labels
    
    return df

def kmeans_predict(df, n_cluster, tsne_x, tsne_y): #predict the cluster of user_input after tsne processing
    km_df=df[["x","y"]].to_numpy()
    user_input=[[tsne_x,tsne_y]]
    df_user_input= pd.DataFrame(user_input)
    kmeans = KMeans(n_clusters=n_cluster, random_state = 0)
    kmeans.fit(km_df)
    user_cluster = kmeans.predict(df_user_input)
    return user_cluster 

def user_cluster_distance(df, n_cluster, tsne_x, tsne_y): #combine the function kmeans_df_labels with kmeans_predict
    user_cluster = kmeans_predict(df, n_cluster, tsne_x, tsne_y)
    a=user_cluster.tolist()
    df=kmeans_df_labels(df, n_cluster)
    rows = df.loc[df['labels']==a[0]] #search for cluster that match with user's predicted cluster
    array_df=rows.to_numpy() #convert to array for iteration
    distance_list=[]
    for i in array_df:
        Euclidean_distance=distance.euclidean((i[0],i[1]),(tsne_x, tsne_y)) 
        distance_list.append(Euclidean_distance)
    new_array= pd.DataFrame(array_df, columns=['x','y','img_name','cluster'])#convert to df again
    new_array['distance Euclidean']=distance_list
    similar_image=new_array.nsmallest(10, 'distance Euclidean').reset_index(drop=True)
    return similar_image
        
def update_js(df, n_cluster, tsne_x, tsne_y): #update latest sequence 
    image_sequence=user_cluster_distance(df, n_cluster, tsne_x, tsne_y)
    image_sequence.to_json("sequence.js",orient='index')
    

update_js(tsne_2d, 6, -0.929617,-6.900858)