In [50]:
from sklearn.cluster import KMeans
import pandas as pd
import hdbscan
import json
import numpy as np
from scipy.spatial import distance
from sklearn.manifold import TSNE

ModuleNotFoundError: No module named 'hdbscan'

In [51]:
#get data out 
import pandas as pd

def read_data(file_path):
    df = pd.read_csv(file_path, header=[0,1], index_col=0)
    return df

df_01= read_data("./NOWHERE_DATASET_copy.csv")
df_01.head(5)
img_name=df_01['Name']

train_df=pd.read_csv("tsne_train.csv")
train_df_1= train_df.drop(['Unnamed: 0'],axis=1)
train_tsne_final=train_df_1.drop(index=0).reset_index(drop=True)
train_tsne_final

,GEOGRAPHY,GEOGRAPHY.1,GEOGRAPHY.2,GEOGRAPHY.3,GEOGRAPHY.4,REALITY,REALITY.1,REALITY.2,REALITY.3,REALITY.4,...,CONTENT TO ME.23,CONTENT TO ME.24,CONTENT TO ME.25,CONTENT TO ME.26,CONTENT TO ME.27,CONTENT TO ME.28,CONTENT TO ME.29,CONTENT TO ME.30,CONTENT TO ME.31,CONTENT TO ME.32
0,1,0,0,0,0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1,0,0,0,0,0.0,0.0,0.5,0.5,0.5,...,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.3,0.0,0.0
2,1,0,0,0,0,0.5,0.0,0.5,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,0,0,0,1,0,0.8,0.0,0.0,1.0,0.0,...,0.0,0.0,0.8,0.3,1.0,0.5,1.0,0.5,1.0,1.0
216,0,0,0,1,0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.5,0.5,0.3,0.7,0.2,0.0,0.0,0.2
217,0,0,0,1,0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.8,1.0,1.0,0.2,0.5,0.0,0.0,0.0
218,0,0,0,1,0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.5,0.0,0.0,0.0,0.5,0.3,0.0,0.2,0.0
219,1,0,0,0,0,0.5,0.5,0.7,1.0,1.0,...,0.0,0.5,0.0,0.5,1.0,1.0,1.0,0.0,0.0,0.0

In [52]:
"""CHANGE IT. THIS IS WHERE USER INPUTS WERE GIVEN, SHOULD BE IN THE FORMAT OF LIST"""

user_input_vector=[1 , 0. , 0. , 0. , 0. , 0.5, 0. , 0.5, 1. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0.5, 0.5, 0. , 0. , 0.5,
        0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5 , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. ]

In [53]:
import pandas as pd

def read_data(file_path):
    df = pd.read_csv(file_path, header=[0,1], index_col=0)
    return df

df_01= read_data("./NOWHERE_DATASET_copy.csv")
df_01.head(5)
img_name=df_01['Name']

train_df=pd.read_csv("tsne_train.csv")
train_df_1= train_df.drop(['Unnamed: 0'],axis=1)
train_tsne_final=train_df_1.drop(index=0).reset_index(drop=True)
train_tsne_final.head(3)

,GEOGRAPHY,GEOGRAPHY.1,GEOGRAPHY.2,GEOGRAPHY.3,GEOGRAPHY.4,REALITY,REALITY.1,REALITY.2,REALITY.3,REALITY.4,...,CONTENT TO ME.23,CONTENT TO ME.24,CONTENT TO ME.25,CONTENT TO ME.26,CONTENT TO ME.27,CONTENT TO ME.28,CONTENT TO ME.29,CONTENT TO ME.30,CONTENT TO ME.31,CONTENT TO ME.32
0,1,0,0,0,0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1,0,0,0,0,0.0,0.0,0.5,0.5,0.5,...,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.3,0.0,0.0
2,1,0,0,0,0,0.5,0.0,0.5,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [54]:

 
 #train tsne everytime a new user_input_vector is given  
def do_TSNE(user_input_vector,data,output_dims, verbose=2, perplexity=30):
    """
    Reduce the dimensionaly from data.colmns into to output_dims
    Returns a numpy array of (len(data), output_dims)    
    """
    df_uservector=pd.DataFrame(np.array(user_input_vector).reshape(-1,len(user_input_vector)))#flat to row pd dataframe
    dataframe = pd.concat([data, df_uservector]).fillna(0).reset_index(drop=True)
    tsne = TSNE(n_components=output_dims, random_state=0, verbose=verbose, perplexity=perplexity)
    data_2d = tsne.fit_transform(dataframe) 
    data_2d_df= pd.DataFrame(data_2d,columns=['x','y'])
    
    dataframe=dataframe.drop(index=220).reset_index(drop=True)
    
    return data_2d_df #contains the user input and user input is at the bottom 
    

results_original = do_TSNE(user_input_vector,train_tsne_final, 2)

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 221 samples in 0.001s...
[t-SNE] Computed neighbors for 221 samples in 0.019s...
[t-SNE] Computed conditional probabilities for sample 221 / 221
[t-SNE] Mean sigma: 1.037879
[t-SNE] Computed conditional probabilities in 0.010s
[t-SNE] Iteration 50: error = 65.1744919, gradient norm = 0.4684525 (50 iterations in 0.059s)
[t-SNE] Iteration 100: error = 63.2482033, gradient norm = 0.5122522 (50 iterations in 0.065s)
[t-SNE] Iteration 150: error = 63.9237633, gradient norm = 0.4952604 (50 iterations in 0.059s)
[t-SNE] Iteration 200: error = 63.4083214, gradient norm = 0.4953247 (50 iterations in 0.063s)
[t-SNE] Iteration 250: error = 66.5563965, gradient norm = 0.4817405 (50 iterations in 0.059s)
[t-SNE] KL divergence after 250 iterations with early exaggeration: 66.556396
[t-SNE] Iteration 300: error = 1.0858966, gradient norm = 0.0062315 (50 iterations in 0.055s)
[t-SNE] Iteration 350: error = 0.8132395, gradient norm = 0.0062798 (50 iterations in 0.051s)
[t-SNE] Iteration 400: error = 0.7300786, gradient norm = 0.0048955 (50 iterations in 0.049s)
[t-SNE] Iteration 450: error = 0.7062341, gradient norm = 0.0008509 (50 iterations in 0.052s)
[t-SNE] Iteration 500: error = 0.7050149, gradient norm = 0.0005808 (50 iterations in 0.053s)
[t-SNE] Iteration 550: error = 0.7047921, gradient norm = 0.0006094 (50 iterations in 0.053s)
[t-SNE] Iteration 600: error = 0.7047791, gradient norm = 0.0002458 (50 iterations in 0.055s)
[t-SNE] Iteration 650: error = 0.7049011, gradient norm = 0.0001632 (50 iterations in 0.052s)
[t-SNE] Iteration 700: error = 0.7047462, gradient norm = 0.0003118 (50 iterations in 0.049s)
[t-SNE] Iteration 750: error = 0.7049045, gradient norm = 0.0002566 (50 iterations in 0.048s)
[t-SNE] Iteration 800: error = 0.7048767, gradient norm = 0.0002520 (50 iterations in 0.051s)
[t-SNE] Iteration 850: error = 0.7047232, gradient norm = 0.0002893 (50 iterations in 0.048s)
[t-SNE] Iteration 900: error = 0.7048165, gradient norm = 0.0002301 (50 iterations in 0.050s)
[t-SNE] Iteration 950: error = 0.7049448, gradient norm = 0.0002203 (50 iterations in 0.052s)
[t-SNE] Iteration 1000: error = 0.7008935, gradient norm = 0.0007569 (50 iterations in 0.052s)
[t-SNE] KL divergence after 1000 iterations: 0.700894

In [55]:
def seperate_user_input(img_name_df): #this function seperates the tsne results of images and tsne result of user input
    results_original = do_TSNE(user_input_vector,train_tsne_final, 2)  
    image_tsne= results_original[:220] # tsne results of all the images 
    image_tsne['img']=img_name
    user_tsne=results_original[220:] #tsne results of user input 
    return image_tsne,user_tsne
image_and_user=seperate_user_input(img_name)

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 221 samples in 0.001s...
[t-SNE] Computed neighbors for 221 samples in 0.020s...
[t-SNE] Computed conditional probabilities for sample 221 / 221
[t-SNE] Mean sigma: 1.037879
[t-SNE] Computed conditional probabilities in 0.010s
[t-SNE] Iteration 50: error = 65.1744919, gradient norm = 0.4684525 (50 iterations in 0.062s)
[t-SNE] Iteration 100: error = 63.2482033, gradient norm = 0.5122522 (50 iterations in 0.065s)
[t-SNE] Iteration 150: error = 63.9237633, gradient norm = 0.4952604 (50 iterations in 0.063s)
[t-SNE] Iteration 200: error = 63.4083214, gradient norm = 0.4953247 (50 iterations in 0.061s)
[t-SNE] Iteration 250: error = 66.5563965, gradient norm = 0.4817405 (50 iterations in 0.061s)
[t-SNE] KL divergence after 250 iterations with early exaggeration: 66.556396
[t-SNE] Iteration 300: error = 1.0858966, gradient norm = 0.0062315 (50 iterations in 0.055s)
[t-SNE] Iteration 350: error = 0.8132395, gradient norm = 0.0062798 (50 iterations in 0.054s)
[t-SNE] Iteration 400: error = 0.7300786, gradient norm = 0.0048955 (50 iterations in 0.054s)
[t-SNE] Iteration 450: error = 0.7062341, gradient norm = 0.0008509 (50 iterations in 0.049s)
[t-SNE] Iteration 500: error = 0.7050149, gradient norm = 0.0005808 (50 iterations in 0.048s)
[t-SNE] Iteration 550: error = 0.7047921, gradient norm = 0.0006094 (50 iterations in 0.048s)
[t-SNE] Iteration 600: error = 0.7047791, gradient norm = 0.0002458 (50 iterations in 0.052s)
[t-SNE] Iteration 650: error = 0.7049011, gradient norm = 0.0001632 (50 iterations in 0.050s)
[t-SNE] Iteration 700: error = 0.7047462, gradient norm = 0.0003118 (50 iterations in 0.050s)
[t-SNE] Iteration 750: error = 0.7049045, gradient norm = 0.0002566 (50 iterations in 0.057s)
[t-SNE] Iteration 800: error = 0.7048767, gradient norm = 0.0002520 (50 iterations in 0.054s)
[t-SNE] Iteration 850: error = 0.7047232, gradient norm = 0.0002893 (50 iterations in 0.055s)
[t-SNE] Iteration 900: error = 0.7048165, gradient norm = 0.0002301 (50 iterations in 0.056s)
[t-SNE] Iteration 950: error = 0.7049448, gradient norm = 0.0002203 (50 iterations in 0.051s)
[t-SNE] Iteration 1000: error = 0.7008935, gradient norm = 0.0007569 (50 iterations in 0.050s)
[t-SNE] KL divergence after 1000 iterations: 0.700894

/Users/Luuk/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [56]:
cluster_df_image=image_and_user[0] #updated image dataframe from tsne 
tsne_x= image_and_user[1]['x'].tolist()[0]
tsne_y=image_and_user[1]['y'].tolist()[0]

In [60]:
#Kmeans on TSNE RESULTS
# def k_means_process (df, n_cluster):
    
def kmeans_df_labels(df, n_cluster): #create a tsne result dataframe with Kmeans cluster label 
    
    km_df=df[["x","y"]].to_numpy()
    Kmeans_result=KMeans(n_clusters=n_cluster, random_state = 0).fit(km_df)
    labels= Kmeans_result.labels_
    df['labels']=labels
    
    return df

def kmeans_predict(df, n_cluster, tsne_x, tsne_y): #predict the cluster of user_input after tsne processing
    km_df=df[["x","y"]].to_numpy()
    user_input=[[tsne_x,tsne_y]]
    df_user_input= pd.DataFrame(user_input)
    kmeans = KMeans(n_clusters=n_cluster, random_state = 0)
    print(km_df.head(20))
    kmeans.fit(km_df)
    user_cluster = kmeans.predict(df_user_input)
    return user_cluster 

def user_cluster_distance(df, n_cluster, tsne_x, tsne_y): #combine the function kmeans_df_labels with kmeans_predict
    user_cluster = kmeans_predict(df, n_cluster, tsne_x, tsne_y)
    a=user_cluster.tolist()
    df=kmeans_df_labels(df, n_cluster)
    rows = df.loc[df['labels']==a[0]] #search for cluster that match with user's predicted cluster
    array_df=rows.to_numpy() #convert to array for iteration
    distance_list=[]
    for i in array_df:
        Euclidean_distance=distance.euclidean((i[0],i[1]),(tsne_x, tsne_y)) 
        distance_list.append(Euclidean_distance)
    new_array= pd.DataFrame(array_df, columns=['x','y','img_name','cluster'])#convert to df again
    new_array['distance Euclidean']=distance_list
    similar_image=new_array.nsmallest(10, 'distance Euclidean').reset_index(drop=True) #you can define how many images you want to return here
    return list(similar_image['img_name']+'.jpg')
        
# def update(df, n_cluster, tsne_x, tsne_y): #update latest sequence 
#     image_sequence=user_cluster_distance(df, n_cluster, tsne_x, tsne_y)
#     image_sequence.to_json("sequence",orient='index')

In [61]:
"""tsne_x and tsne_y will be changed automatically, cluster we need to define ourselves. You only need to change the user input"""
user_cluster_distance(cluster_df_image, 6, tsne_x,tsne_y)

AttributeError: 'numpy.ndarray' object has no attribute 'head'